### ISSUE TITLE
./.nuxt/client.js配置需要怎样修改才能运行？

### ISSUE THREAD

**Issue by weiqihao** [justyeh/justyeh.com#15]
```
 ERROR  Failed to compile with 1 errors
 error  in ./.nuxt/client.js

Module build failed: Error: Couldn't find preset "vue-app" relative to directory
 "E:\\justyeh.com\\.nuxt"
    at E:\justyeh.com\node_modules\babel-core\lib\transformation\file\options\op
tion-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\justyeh.com\node_modules\babel-core\lib\
transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\justyeh.com\node_modules\babel-core\lib\tr
ansformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\justyeh.com\node_modules\babel-core\lib\tr
ansformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\justyeh.com\node_modules\babel-core\lib\transforma
tion\file\options\option-manager.js:368:12)
    at File.initOptions (E:\justyeh.com\node_modules\babel-core\lib\transformati
on\file\index.js:212:65)
    at new File (E:\justyeh.com\node_modules\babel-core\lib\transformation\file\
index.js:135:24)
    at Pipeline.transform (E:\justyeh.com\node_modules\babel-core\lib\transforma
tion\pipeline.js:46:16)
    at transpile (E:\justyeh.com\node_modules\babel-loader\lib\index.js:46:20)
    at E:\justyeh.com\node_modules\babel-loader\lib\fs-cache.js:79:18
    at ReadFileContext.callback (E:\justyeh.com\node_modules\babel-loader\lib\fs
-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js
```

**Comment by justyeh** [comment]
我好久没看nxut的内容了，我当时使用的版本（rc3）并没有这个配置项，如果你用的不是该版本，应该是版本直接API冲突造成的，请查看最新文档！

**Comment by weiqihao** [comment]
"nuxt": "version": "1.0.0-alpha.3",是不是还有那个插件没锁死版本造成的？
